services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8070}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=${POSTGRES_USER:-odoo}
      - PASSWORD=${POSTGRES_PASSWORD:-odoo}

  db:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
    volumes:
      - odoo-db:/var/lib/postgresql/data

volumes:
  odoo-db: