[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$QcjZ27u3FgLgPAdgTAlhjA$mflwLVomhbeP/w2deiUNEnayd/qevlrokiK/30SSP0ECGlCYWO8chccS8QX/W8IHrmMA/XFxswu5y7BN4VCgyQ

