[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$LgWAMGbMuVcKAcD4fw/hnA$9jEfClcOnfXwMlGGCWl.QmvLgtypZY/wZe5eN/7h/RnVO.o1RQr7peqBk7hI/UqOI98FbUm3mtJ2XFBOSeF8gw

