[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$dE4pxVgrhdB6j/G.VwrBeA$EA.rfQ5g6y0BVSfg./Ko2gKEJ7VV1Q.unBbByOiQmBez/tkGnBZmEyMN6ImAxCsbBjtMoNVlQ/byk4p/tbfr8A

